scrape_configs:
  - job_name: 'EmployeeServiceMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8093' ]
        labels:
          application: 'Employee Service'